/**
 * Data contract for <Instrument />.
 *
 * One JSON document describes a federated slice of a building: which
 * discipline models it is made of, which storeys exist, what classes and
 * materials occur, and one row per product. The component derives every
 * cell from this — it never fetches anything else, and it never reads
 * the GLB for anything but geometry and `extras.guid` / `extras.entity`.
 *
 * Generated by ifcfast (`scripts/generate_receipts.py`) as
 * `receipts/model/instrument.json`.
 */

export type InstrumentModel = {
  /** Discipline name; must equal the `model` field on its products. */
  name: string;
  /** Absolute URL of that discipline's GLB. May 404 — handled. */
  glb: string;
  products: number;
  bytes: number;
};

export type InstrumentStorey = {
  guid: string;
  name: string;
  elevation_m: number;
  /** Product count in the whole model, not only in this slice. */
  products: number;
};

export type InstrumentClass = {
  entity: string;
  model: string;
  n: number;
  volume_m3: number;
};

export type InstrumentMaterial = {
  name: string;
  n: number;
};

export type InstrumentProduct = {
  entity: string;
  model: string;
  storey: string;
  volume_m3: number;
  /** false ⇒ volume_m3 is a prism fallback; route the row elsewhere. */
  volume_reliable: boolean;
  material: string | null;
  clash_partners: string[];
};

export type InstrumentData = {
  generated: string;
  ifcfast_version: string;
  scope: string;
  poster?: string;
  models: InstrumentModel[];
  storeys: InstrumentStorey[];
  classes: InstrumentClass[];
  materials: InstrumentMaterial[];
  products: Record<string, InstrumentProduct>;
};

/** What the viewport is asked to show. `null` = nothing filtered. */
export type ViewportFilter = {
  /** Guids that stay lit. `null` means every guid stays lit. */
  active: Set<string> | null;
  /** The one guid drawn in the accent colour. */
  selected: string | null;
};
