import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

// IBM Plex was drawn for technical communication: the sans and the mono
// are the same design, so a table of numbers and the sentence above it
// look like one document rather than two fonts sharing a page.
const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap",
});

const SITE_URL = "https://ifcfast.com";
const SITE_TITLE = "ifcfast — an open IFC parser for data, geometry, and writing";
const OG_DESCRIPTION =
  "An open IFC toolkit. IFC → pandas, meshes, point clouds, clash facts — and surgical edits written back as valid IFC. Under active development — contributions welcome.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  description:
    "An open IFC toolkit with a Python API. Reads IFC data and geometry into pandas, meshes, and point clouds; writes surgical subsets, mesh swaps, and attribute edits back to valid IFC; runs clash detection over a parquet substrate. Differential-tested against ifcopenshell and Solibri on real models. Built for agents, analytics, and pipelines.",
  keywords: [
    "IFC", "BIM", "parser", "AEC", "Rust", "Python", "MCP",
    "AI agents", "ifcopenshell", "spatial graph", "point cloud", "mesh",
    "clash detection", "IFC writer", "glTF", "parquet", "DuckDB",
    "quantity takeoff",
  ],
  authors: [{ name: "Edvard Granskogen Kjorstad" }],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: SITE_TITLE,
    description: OG_DESCRIPTION,
    type: "website",
    url: SITE_URL,
    siteName: "ifcfast",
    // og:image is generated by app/opengraph-image.tsx and wired automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: OG_DESCRIPTION,
    // twitter:image reuses the generated Open Graph image.
    images: ["/opengraph-image"],
  },
};

const JSON_LD = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "ifcfast",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Linux, macOS, Windows",
  description:
    "An open IFC toolkit with a Python API. Reads IFC data and geometry into pandas, meshes, and point clouds; writes surgical subsets, mesh swaps, and attribute edits back to valid IFC; runs clash detection over a parquet substrate.",
  url: SITE_URL,
  author: { "@type": "Person", name: "Edvard Granskogen Kjorstad" },
  license: "https://opensource.org/licenses/MIT",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  downloadUrl: "https://pypi.org/project/ifcfast/",
  codeRepository: "https://github.com/EdvardGK/ifcfast",
  programmingLanguage: ["Rust", "Python"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plexSans.variable} ${plexMono.variable} antialiased`}
    >
      <body className="bg-paper text-ink font-sans min-h-screen selection:bg-accent-tint selection:text-ink">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:bg-ink focus:px-4 focus:py-2 focus:text-sm focus:text-paper"
        >
          Skip to content
        </a>
        {children}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
      </body>
    </html>
  );
}
