import type { Metadata } from "next";
import { JetBrains_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const SITE_URL = "https://ifcfast.com";
const OG_DESCRIPTION =
  "An open, experimental IFC parser. IFC → pandas, meshes, point clouds. Early and under active development — contributions welcome.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "ifcfast — an open IFC parser for data and geometry",
  description:
    "An open, experimental IFC parser with a Python API. Reads IFC data and geometry into pandas, meshes, and point clouds — no geometry kernel on the hot path. Built for agents, analytics, and pipelines. Early and under active development.",
  keywords: [
    "IFC", "BIM", "parser", "AEC", "Rust", "Python", "MCP",
    "AI agents", "ifcopenshell", "spatial graph", "point cloud", "mesh",
  ],
  authors: [{ name: "Edvard Granskogen Kjorstad" }],
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "ifcfast — an open IFC parser for data and geometry",
    description: OG_DESCRIPTION,
    type: "website",
    url: SITE_URL,
    siteName: "ifcfast",
    // og:image is generated by app/opengraph-image.tsx and wired automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: "ifcfast — an open IFC parser for data and geometry",
    description: OG_DESCRIPTION,
    // twitter:image reuses the generated Open Graph image.
    images: ["/opengraph-image"],
  },
};

const JSON_LD = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "ifcfast",
  applicationCategory: "DeveloperApplication",
  operatingSystem: "Linux, macOS, Windows",
  description:
    "An open, experimental IFC parser with a Python API. Reads IFC data and geometry into pandas, meshes, and point clouds — no geometry kernel on the hot path.",
  url: SITE_URL,
  author: { "@type": "Person", name: "Edvard Granskogen Kjorstad" },
  license: "https://opensource.org/licenses/MIT",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  downloadUrl: "https://pypi.org/project/ifcfast/",
  codeRepository: "https://github.com/EdvardGK/ifcfast",
  programmingLanguage: ["Rust", "Python"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
    >
      <body className="bg-bg text-fg font-sans min-h-screen flex flex-col selection:bg-accent/40 selection:text-fg">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:rounded-md focus:bg-fg focus:px-4 focus:py-2 focus:text-sm focus:text-bg"
        >
          Skip to content
        </a>
        {children}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
      </body>
    </html>
  );
}
